### ISSUE TITLE
img2paa is broken

### ISSUE THREAD

**Issue by Krzmbrzl** [KoffeinFlummi/armake2#61]
Using latest master (12dd97bef9a111def31777b41d97d38e29a6ad1e) the following command
```
RUST_BACKTRACE=full armake2 img2paa coopetition_10.jpg test.paa
```
results in this output (on Linux):

```
thread 'main' panicked at 'internal error: entered unreachable code', src/run.rs:184:9
stack backtrace:
   0:     0x561cce6427d0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x561cce6427d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x561cce6427d0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x561cce6427d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x561cce662eec - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x561cce63f937 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x561cce644920 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x561cce644920 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x561cce644920 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x561cce64466c - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x561cce644f83 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x561cce57ccb4 - std::panicking::begin_panic::{{closure}}::hf29ff657fabbf917
  12:     0x561cce57c57c - std::sys_common::backtrace::__rust_end_short_backtrace::h3c1ac6bd66520561
  13:     0x561cce57cc8c - std::panicking::begin_panic::h60d662959019e8ba
  14:     0x561cce561e44 - armake2::run::args::h383e7cb2e87cbefa
  15:     0x561cce5330c9 - armake2::main::h2458abe772ffde6b
  16:     0x561cce52da53 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd5e724ffb61b081e
  17:     0x561cce52d9e9 - std::rt::lang_start::{{closure}}::hb457747f11fd642c
  18:     0x561cce645381 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  19:     0x561cce645381 - std::panicking::try::do_call::h88ce358792b64df0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  20:     0x561cce645381 - std::panicking::try::h6311c259678e50fc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  21:     0x561cce645381 - std::panic::catch_unwind::h56c5716807d659a1
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  22:     0x561cce645381 - std::rt::lang_start_internal::h73711f37ecfcb277
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  23:     0x561cce5331c2 - main
  24:     0x7f5c3e67a0b3 - __libc_start_main
  25:     0x561cce52d0ae - _start
  26:                0x0 - <unknown>
```

I have attached the respective JPEG to this post.
![coopetition_10](https://user-images.githubusercontent.com/12751591/97784477-3356ab00-1b9f-11eb-95f9-bf8fd39007d1.jpg)

**Comment by Krzmbrzl** [comment]
From a look at the code it seems `img2paa` isn't even implemented :eyes:

**Comment by jokoho48** [comment]
from the readme: 
> Status: PAA commands not implemented, some options not implemented, testing.

**Comment by Krzmbrzl** [comment]
Well in that case it shouldn't show up in the command list or at least output that it is not implemented when called instead of crashing the program
